# The SuperNet part is initialized directly in `roberta/model.py`
# E.g. "roberta_small":
#    args.encoder_layers = safe_getattr(args, "encoder_layers", 6)
#    args.encoder_embed_dim = safe_getattr(args, "encoder_embed_dim", 512)
#    args.encoder_ffn_embed_dim = safe_getattr(args, "encoder_ffn_embed_dim", 2048)
#    args.encoder_attention_heads = safe_getattr(args, "encoder_attention_heads", 8)

# TODO: Add the ability to initialize supernet from the numbers here
# SUPERNET:
#  EMBED_DIM:
#  NUM_HEADS:
#  FFN_EMBED_DIM:
#  DEPTH:

# The Search space for the subnets
SEARCH_SPACE:
  EMBED_DIM:
    - 256
    - 384
    - 512
  NUM_HEADS:
    - 4
    - 8
  FFN_EMBED_DIM:
    - 1024
    - 1536
    - 2048
  DEPTH:
    - 4
    - 5
    - 6